# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71e018a0f38bf017d9db126f84deaf251f13bd3aeb9edcd87ceeeab02f3195d4831e4f1238d8578b6c63bc6647c3a42cb69a4b1eee5e09dd1cedb8a4a07ae49c

test:
  secret_key_base: 9d876f96df79bde14ee948e0a8a83eb13eab59a346099ba5a2051d3fbf7e0305cf0cd44452282ab4617f98ce20a3a4d231703a3c26b582d8e66eb659da206435

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
